<?php
/**
 * @file
 * Code for the Directnews feature.
 */

include_once 'directnews.features.inc';



/**
 * Implemention of hook_feeds_plugins().
 */
function directnews_feeds_plugins(){
  $info = array();

  $info['DirectnewsParser'] = array(
    'name' => 'Directnews parser',
    'description' => 'Parse directnews feeds',
    'help' => 'Parse directnews feeds',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'DirectnewsParser',
      'file' => 'DirectnewsParser.inc',
      'path' => drupal_get_path('module', 'directnews'),
    ),
  );

  return $info;
}

function directnews_feeds_enable(){
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
